# Generated by Django 3.2.12 on 2024-02-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceShare', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(default='No  Comment Provided', max_length=512),
        ),
    ]
