# Generated by Django 3.2.12 on 2024-02-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceShare', '0005_trustrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrustRating',
        ),
    ]
