# Generated by Django 3.2.12 on 2024-02-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceShare', '0007_trustrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='trustRating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TrustRating',
        ),
    ]
