# Generated by Django 3.2.12 on 2024-02-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceShare', '0008_auto_20240212_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='downloadCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
