# Generated by Django 3.2.12 on 2024-02-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceShare', '0009_customuser_downloadcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='downloadCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='trustRating',
            field=models.FloatField(default=0),
        ),
    ]
