# Generated by Django 3.2.12 on 2024-02-20 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceShare', '0012_savedresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('trustee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_relationships_as_trustee', to=settings.AUTH_USER_MODEL)),
                ('trustor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_relationships_as_trustor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
