# Generated by Django 3.2.12 on 2024-02-25 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceShare', '0014_trustrelationship_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustrelationship',
            name='relatedResource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ResourceShare.resource'),
        ),
    ]
