# Generated by Django 3.2.12 on 2024-02-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceShare', '0015_trustrelationship_relatedresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.TextField(default='Other', max_length=512),
        ),
    ]
